yatube/about/urls.py
from django.urls import path
from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [

    path('', views.index, name='index'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('group/<str:slug>/', views.group_posts, name='group_list'),
    path(
        'posts/<int:post_id>/comment/',
        views.add_comment, name='add_comment'),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/users/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
    path('logout/', LogoutView.as_view(
        template_name='users/logged_out.html'), name='logout'),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls', namespace='posts')),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about'))
]

handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'


if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="icon" href={% static 'img/fav/fav.ico' %}" type="image">
    <link
      rel="apple-touch-icon"
      sizes="180x180"
      href="{% static 'img/fav/apple-touch-icon.png' %}"
    />
    <link
      rel="icon"
      type="image/png"
      sizes="32x32"
      href="{% static 'img/fav/favicon-32x32.png' %}"
    />
    <link
      rel="icon"
      type="image/png"
      sizes="16x16"
      href="{% static 'img/fav/favicon-16x16.png' %}"
    />
    <meta name="msapplication-TileColor" content="#da532c" />
    <meta name="theme-color" content="#ffffff" />
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />
    <title>
      {% block title %} Последние обновления на сайте {% endblock %}
    </title>
  </head>
  <body>
    {% include 'nav.html' %}
    <main>
      <div class="container py-5">
        <h1>
          {% block header %}The Last Social Media You'll Ever Need{% endblock %}
        </h1>
        {% block content %}
        <!-- Содержимое страницы -->
        {% endblock %}
      </div>
    </main>
    {% include 'footer.html' %}
  </body>
</html>

yatube/templates/comment.html
{% load user_filters %}
{% if user.is_authenticated %}
  <div class="card my-4">
    <h5 class="card-header">Добавить комментарий:</h5>
    <div class="card-body">
      <form method="post" action="{% url 'posts:add_comment' post.id %}">
        {% csrf_token %}      
        <div class="form-group mb-2">
          {{ form.text|addclass:"form-control" }}
        </div>
        <button type="submit" class="btn btn-primary">Отправить</button>
      </form>
    </div>
  </div>
{% endif %}

{% for comment in comments %}
  <div class="media mb-4">
    <div class="media-body">
      <h5 class="mt-0">
        <a href="{% url 'posts:profile' comment.author.username %}">
          {{ comment.author.username }}
        </a>
      </h5>
        <p>
         {{ comment.text|linebreaksbr }}
        </p>
      </div>
    </div>
{% endfor %}

yatube/templates/footer.html
<footer class="pt-4 my-md-5 pt-md-5 border-top">
  <p class="m-0 text-dark text-center">
    <a href="{% url 'about:author' %}">Об авторе</a>
    <a href="{% url 'about:tech' %}">Технологии</a>
  </p>
  <p class="m-0 text-dark text-center">
    © {{ year }} Copyright Социальная сеть
    <span style="color: black">Ya</span>tube
  </p>
</footer>

yatube/templates/nav.html
{% load static %}
<header>
  <nav class="navbar navbar-light" style="background-color: #b0e2ff"  >
    <div class="container">
      <a class="navbar-brand" href="{% url 'posts:index' %}">
        <img
          src="{% static 'img/logo.png' %}"
          width="30"
          height="30"
          class="d-inline-block align-top"
          alt=""
        />
        <span style="color: white">Ya</span>tube
      </a>
      <ul class="nav nav-pills">
        {% with request.resolver_match.view_name as view_name %}
        <li class="nav-item">
          <a
            class="nav-link {% if view_name == 'about:author' %} active {% endif %}"
            href="{% url 'about:author' %}"
            >Автор</a
          >
        </li>
        <li class="nav-item">
          <a
            class="nav-link {% if view_name == 'about:tech' %} active {% endif %}"
            href="{% url 'about:tech' %}"
            >Технологии</a
          >
        </li>
        {% endwith %} {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'posts:post_create' %}"
            >Новая запись</a
          >
        </li>
        <li class="nav-item">
          <a class="nav-link link-light" href="{% url 'password_change' %}"
            >Изменить пароль</a
          >
        </li>
        <li class="nav-item">
          <a class="nav-link link-light" href="{% url 'logout' %}">Выйти</a>
        </li>
        <li class="nav-link link-dark">
          Пользователь:
          <a href="{% url 'posts:profile' user.username %}"
            >{{ user.username }}</a
          >
        </li>

        <li>{% else %}</li>

        <li class="nav-item">
          <a class="nav-link link-light" href="{% url 'login' %}">Войти</a>
        </li>
        <li class="nav-item">
          <a class="nav-link link-light" href="{% url 'users:signup' %}"
            >Регистрация</a
          >
        </li>
        {% endif %}
      </ul>
    </div>
  </nav>
</header>