yatube/about/urls.py
from django.urls import path
from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [

    path('', views.index, name='index'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('group/<str:slug>/', views.group_posts, name='group_list'),
    path(
        'posts/<int:post_id>/comment/',
        views.add_comment, name='add_comment'),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls', namespace='posts')),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about'))
]

handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'


if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200, verbose_name='Заголовок')
    description = models.TextField(verbose_name="Описание")
    slug = models.SlugField(unique=True, verbose_name='Ярлык')

    class Meta:
        verbose_name_plural = "Группы"
        verbose_name = 'Группа'

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField(verbose_name='Текст поста')
    pub_date = models.DateTimeField(
        auto_now_add=True,
        verbose_name="Дата публикации"
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор'
    )
    group = models.ForeignKey(
        Group,
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        related_name='posts',
        verbose_name='Группа'
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )

    class Meta:
        ordering = ['-pub_date']
        verbose_name_plural = 'Посты'
        verbose_name = 'Пост'

    def __str__(self):
        return self.text[:15]


class Comment(models.Model):
    text = models.TextField(
        'Текст поста',
        help_text='Введите текст для поста'
    )
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Комментарии'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Автор комментария'
    )
    created = models.DateTimeField(
        'Дата публикации',
        auto_now_add=True
    )

    class Meta:
        ordering = ['-created']
        verbose_name_plural = 'Коментарии'
        verbose_name = 'Коментарий'

    def __str__(self):
        return self.text[:15]


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following'
    )

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=['user', 'author'],
                name="unique_followers")
        ]

yatube/posts/forms.py
from django.forms import ModelForm
from .models import Post
from .models import Comment


class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = [
            'group',
            'text',
            'image',
        ]
        labels = {
            'group': 'Выберите группу',
            'text': 'Текст поста',
            'image': 'Изображение'
        }


class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ['text']
        labels = {
            'text': 'Текст поста',
        }

yatube/posts/views.py
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect, render
from .forms import CommentForm, PostForm
from .models import Post, Group, Follow, User
from django.views.decorators.cache import cache_page


def paginator_func(posts, request):
    paginator = Paginator(posts, 10)
    page_number = request.GET.get('page')
    return paginator.get_page(page_number)


@cache_page(60 * 20)
def index(request):
    post_list = Post.objects.select_related('author', 'group').all()
    page_obj = paginator_func(post_list, request)
    return render(request, 'posts/index.html', {'page_obj': page_obj})


def group_posts(request, slug):
    """Возращаем 10 постов"""
    group = get_object_or_404(Group, slug=slug)
    all_post = group.posts.all()
    page_obj = paginator_func(all_post, request)

    return render(
        request,
        'posts/group_list.html',
        {'page_obj': page_obj, 'group': group})


def profile(request, username):
    """Показываем профиль пользователя"""
    author = get_object_or_404(User, username=username)
    posts_all = author.posts.all()
    page_obj = paginator_func(posts_all, request)
    following = (request.user.is_authenticated and author != request.user
                 and Follow.objects.filter(user=request.user,
                                           author=author).exists())
    return render(request, 'posts/profile.html', {
        'page_obj': page_obj,
        'author': author,
        'following': following,
    })


def post_detail(request, post_id):
    """Показываем пост"""
    post = get_object_or_404(Post, id=post_id)
    comments = post.comments.select_related('author')
    form = CommentForm()
    return render(request, 'posts/post_detail.html', {
        'post': post,
        'comments': comments,
        'form': form,
    })


@login_required
def post_create(request):
    """Создаём новый пост"""
    form = PostForm(request.POST or None, files=request.FILES or None)
    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()
        return redirect('posts:profile', username=request.user.username)
    return render(request, 'posts/create_post.html', {
        'form': form
    })


@login_required
def post_edit(request, post_id):
    """Редактируем пост."""
    post = get_object_or_404(Post, id=post_id)
    if post.author != request.user:
        return redirect('posts:post_detail', post_id=post_id)

    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post
    )
    if form.is_valid():
        form.save()
        return redirect('posts:post_detail', post_id=post_id)
    return render(request, 'posts/create_post.html', {
        'post': post,
        'form': form,
        'is_edit': True,
    })


@login_required
def add_comment(request, post_id):
    """Комментарии."""
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    post_list = Post.objects.filter(author__following__user=request.user)
    page_obj = paginator_func(post_list, request)
    return render(request, 'posts/follow.html', {'page_obj': page_obj})


@login_required
def profile_follow(request, username):
    """Подписки."""
    author = get_object_or_404(User, username=username)
    if author != request.user:
        Follow.objects.get_or_create(author=author, user=request.user)
    return redirect('posts:profile', author)


@login_required
def profile_unfollow(request, username):
    """Отписка."""
    get_object_or_404(Follow, user=request.user,
                      author__username=username).delete()
    return redirect('posts:profile', username=username)

yatube/templates/posts/create_post.html
{% extends "base.html" %}
{% block title %}
  {% if is_edit %} Редактировать запись {% else %} Новый пост{% endif %}
{% endblock %}
{% block header %}
  {% if is_edit %}Редактировать запись{% else %}Создание нового поста{% endif %}
{% endblock %}
{% block content %}
  <main>
    <div class="container py-5">
      <div class="row justify-content-center">
        <div class="col-md-8 p-5">
          <div class="card">
            <div class="card-header">       
              {% if is_edit %} Редактировать запись {% else %} Добавить запись {% endif %}            
            </div>
            <div class="card-body"> 
              <form method="post" action=" " enctype="multipart/form-data">
                {% csrf_token %}
                {% for field in form %}
                  <div class="form-group row my-3 p-3">
                    <label for="id_group">
                      {{ field.label }}
                      {% if field.field.required %}
                        *
                      {% endif %}              
                    </label>
                    {{ field }}
                    {{ field.help_text }}
                  </div>
                {% endfor %}            
                <div class="d-flex justify-content-end">
                  <button type="submit" class="btn btn-primary">
                    {% if is_edit %}Сохранить {% else %}Добавить{% endif %}
                  </button>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </main>
{% endblock %}

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% block title %}
  {{ title }}
{% endblock %} 
{% block content %}
  {% include 'posts/includes/switcher.html' %}
  {% load thumbnail %}
  {% for post in page_obj %}
  <div class="align="left"">
    <ul>
    <li>
      <b>Автор:</b>
      <a href="{% url 'posts:profile' post.author %}">{{ post.author.get_full_name }}</a>
    </li>
    <li>
      <b>Дата публикации:</b> {{ post.pub_date|date:"d E Y" }}
    </li>
    {% if post.group %}
    <li>
      <p><b>Группа:</b> 
      <a href="{% url 'posts:group_list' post.group.slug %}">{{ post.group.title }}</a></p>
    </li>
    {% endif %}
    </ul>
    {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
      <img class="card-img my-2" src="{{ im.url }}">
    {% endthumbnail %}
    <p>{{ post.text|linebreaks }}</p>
    <a href="{% url 'posts:post_detail' post.pk %}"class="btn btn-outline-dark">Перейти в пост</a>    
    {% if not forloop.last %}<hr>{% endif %}
  </div>
  {% endfor %}
  {% include 'posts/includes/paginator.html' %}
{% endblock %} 

yatube/templates/posts/group_list.html
{% extends "base.html" %}
{% load thumbnail %}
{% block title %}{{group.title}}{% endblock %}
{% block header %}<h1>{{group.title}}</h1>{% endblock %}
{% block content %}
<p>{{group.description|linebreaksbr}}</p>
  {% for post in page_obj %}
        <ul>
          <li>Автор: <a href="{% url 'posts:profile' post.author.username %}">{{post.author.get_full_name}}</a></li>
          <li>Дата публикации: {{post.pub_date|date:"d M Y" }}</li>
        </ul>
      {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
      {% endthumbnail %}
        <br>
        <p class="card-text">
          {{ post.text|linebreaksbr }}
        </p>
        <a href="{% url 'posts:post_detail' post.id %}" class="btn btn-outline-dark">Перейти в пост</a> 
	<hr>
  {%endfor%}
  {% include 'posts/includes/paginator.html' with page=page_obj %}
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% load thumbnail %}
<h2>{% block title %}The Last Social Media You'll Ever Need{% endblock %}</h2>
<h2>{% block header %}The Last Social Media You'll Ever Need{% endblock %}</h2>
{% block content %}
{% include 'posts/includes/switcher.html' %}
  {% for post in page_obj %}
    <div class="align="left""> 
      <ul>
      <li>
        <b>Автор:</b> 
        <a href="{% url 'posts:profile' username=post.author.username %}"> {{ post.author.get_full_name }}</a>
      </li>
      <li>
        <b>Дата публикации:</b> {{ post.pub_date|date:"d E Y" }}
      </li>
      {% if post.group %}
      <li>
        <p><b>Группа:</b> 
        <a href="{% url 'posts:group_list' post.group.slug %}">{{ post.group.title }}</a></p>
      </li>
      {% endif %}
      </ul>
    {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
      <img class="card-img my-2" src="{{ im.url }}">
    {% endthumbnail %}
    <p class="card-text">
      {{ post.text|linebreaksbr }}
    </p>
    <a href="{% url 'posts:post_detail' post.id %}" class="btn btn-outline-dark">Перейти в пост</a>    
      {% if not forloop.last %}<hr>{% endif %}
    </div>
  {% endfor %}
  {% include 'posts/includes/paginator.html' %}
{% endblock %} 

yatube/templates/posts/post_detail.html
{% extends "base.html" %}
{% load user_filters %}
{% block title %}{{ post.text|truncatechars:30 }}{% endblock %}
{% block content %}
{% load thumbnail %}
  <main role="main" class="container">
    <div class="row">
      <div class="col-md-3 mb-3 mt-1">
        <div class="card">
          <div class="card-body">
            <div class="h2">
              {{post.author.first_name}} {{post.author.last_name}}
            </div>
            <div class="h3 text-muted">
              <a href="{% url 'posts:profile' post.author.username %}">{{post.author.username}}</a>
            </div>
          </div>
          <ul class="list-group list-group-flush">
            <li class="list-group-item">
              <div class="h6 text-muted">
                Подписчиков: XXX <br>
                Подписан: XXX
              </div>
            </li>
            <li class="list-group-item">
              <div class="h6 text-muted">
                Записей: {{ post.author.posts.count }}
              </div>
            </li>
          </ul>
        </div>
      </div>
      <div class="col-md-9">
        <div class="card mb-3 mt-1 shadow-sm">
          <div class="card-body">
            <p class="card-text">
              <a href="{% url 'posts:profile' post.author.username %}">
                <strong class="d-block text-gray-dark">
                  <a href="{% url 'posts:profile' post.author.username %}">@{{post.author.username}}</a>
                </strong>
              </a>
            {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
              <img class="card-img my-2" src="{{ im.url }}">
            {% endthumbnail %}
            <p class="card-text">
              {{ post.text|linebreaksbr }}
            </p>
            {% include 'comment.html' with post=post %}
            <div class="d-flex justify-content-between align-items-center">
              {% if user == post.author %}
                <div class="btn-group">
                  <a class="btn btn-sm text-muted" href="{% url 'posts:post_edit' post_id=post.id  %}" role="button">
                    Редактировать
                  </a>
                </div>
              {% endif %}
              <small class="text-muted">{{post.pub_date|date:"d  Y" }}</small>
              {% if post.group %}
                <p><a href="{% url 'posts:group_list' slug=post.group.slug %}">{{ post.group }}</a></p>
              {% endif %}
            </div>
          </div>
        </div>
      </div>
    </div>
  </main>
{% endblock %}

yatube/templates/posts/profile.html
{% extends "base.html" %}
{% load thumbnail %}
{% block title %}Профиль пользователя {{author.username}}{% endblock %}
{% block content %}
      <div class="container py-5">        
        <h2>Все посты пользователя: {{ author.get_full_name }} </h2>
        <h3>Всего постов: {{ author.posts.count }} </h3>
        {% if following %}
        <a
          class="btn btn-lg btn-light"
          href="{% url 'posts:profile_unfollow' author.username %}" role="button"
        >
          Отписаться
        </a>
      {% else %}
          <a
            class="btn btn-lg btn-primary"
            href="{% url 'posts:profile_follow' author.username %}" role="button"
          >
            Подписаться
          </a>
      {% endif %}
      </div>
      <div class="col-md-9">
        {% for post in page_obj %}
        <article>
          <ul>
            <li>
              Автор: {{ author.get_full_name }}
            </li>
            <li>
              Дата публикации: {{ post.pub_date|date:"d E Y" }}
            </li>
              {% if post.group %}
              <li>
                  <p>Группа:
                  <a href="{% url 'posts:group_list' post.group.slug %}">{{ post.group.title }}</a></p>
              </li>
              {% endif %}
          </ul>
          {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
            <img class="card-img my-2" src="{{ im.url }}">
          {% endthumbnail %}
          <p>
          {{ post.text|linebreaks }}
          <a href="{% url 'posts:post_detail' post.pk %}">Перейти в пост</a>
          </p>
          </article>
          {% if not forloop.last %}<hr>{% endif %}
        {% endfor %}
        {% include 'posts/includes/paginator.html' %}
      </div>
      {% endblock %}